name: Build and Push to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: joseco/az-ml-cli

jobs:
  Build_and_Push_Image:
    runs-on: [ubuntu-22.04]
    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Define TAG
      run: echo "TAG=${{ github.run_number }}.${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Build and Push Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
  


    # - name: Build Docker (local test)
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     load: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}